INSERT INTO tb_missao (data_vencimento, nome, pontuacao) VALUES ('2023-09-02', 'Fazer exercícios', 150);
INSERT INTO tb_missao (data_vencimento, nome, pontuacao) VALUES ('2023-09-02', 'Beber mais água', 100);
INSERT INTO tb_missao (data_vencimento, nome, pontuacao) VALUES ('2023-09-02', 'Estudar programação', 180);
INSERT INTO tb_missao (data_vencimento, nome, pontuacao) VALUES ('2023-09-02', 'Ler um livro', 70);
INSERT INTO tb_missao (data_vencimento, nome, pontuacao) VALUES ('2023-09-02', 'Praticar meditação', 120);
INSERT INTO tb_missao (data_vencimento, nome, pontuacao) VALUES ('2023-09-02', 'Aprender um novo idioma', 90);
INSERT INTO tb_missao (data_vencimento, nome, pontuacao) VALUES ('2023-09-02', 'Cozinhar uma nova receita', 200);
INSERT INTO tb_missao (data_vencimento, nome, pontuacao) VALUES ('2023-09-02', 'Fazer uma caminhada', 80);
INSERT INTO tb_missao (data_vencimento, nome, pontuacao) VALUES ('2023-09-02', 'Escrever um diário', 110);
INSERT INTO tb_missao (data_vencimento, nome, pontuacao) VALUES ('2023-09-02', 'Aprender a tocar um instrumento', 160);
